# Generated by Django 6.1 on 2026-09-02 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('on_time_delivery_pct', models.FloatField(default=0, help_text='Percentage of deliveries completed on time', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cargo_damage_incidents', models.PositiveIntegerField(default=0, help_text='Number of cargo damage claims in last 12 months')),
                ('payment_reliability_pct', models.FloatField(default=0, help_text='Percentage of payments made within agreed terms', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_voyages', models.PositiveIntegerField(default=0, help_text='Total number of completed voyages')),
                ('years_in_operation', models.PositiveIntegerField(default=0)),
                ('trust_score', models.FloatField(default=0, help_text='Computed reliability score (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trust_grade', models.CharField(blank=True, help_text='Letter grade: A+, A, B, C, D, F', max_length=2)),
            ],
            options={
                'ordering': ['-trust_score'],
            },
        ),
        migrations.CreateModel(
            name='MacroFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bunker_fuel_price_usd', models.DecimalField(decimal_places=2, help_text='Crude/Bunker fuel price in USD per ton', max_digits=10)),
                ('port_congestion_index', models.DecimalField(decimal_places=2, help_text='Global port congestion index (0–100 scale)', max_digits=5)),
                ('seasonal_weather_impact', models.DecimalField(decimal_places=2, help_text='Seasonal weather impact score (0–10 scale)', max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_class', models.CharField(choices=[('supramax', 'Supramax'), ('panamax', 'Panamax'), ('capesize', 'Capesize')], max_length=20, unique=True)),
                ('min_dwt', models.PositiveIntegerField(help_text='Minimum Dead Weight Tonnage')),
                ('max_dwt', models.PositiveIntegerField(help_text='Maximum Dead Weight Tonnage')),
                ('typical_draft', models.FloatField(help_text='Typical loaded draft in metres')),
                ('typical_beam', models.FloatField(help_text='Typical beam in metres')),
                ('typical_loa', models.FloatField(help_text='Typical Length Overall in metres')),
            ],
            options={
                'ordering': ['min_dwt'],
            },
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('BDI', 'Baltic Dry Index'), ('BCI', 'Baltic Capesize Index'), ('BPI', 'Baltic Panamax Index'), ('BSI', 'Baltic Supramax Index')], max_length=5)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_pct_24h', models.DecimalField(decimal_places=2, default=0, help_text='24-hour percentage change', max_digits=6)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('index_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('port_type', models.CharField(choices=[('origin', 'Origin (Loading Port)'), ('destination', 'Destination (Indian Port)')], max_length=20)),
                ('max_draft', models.FloatField(default=20.0, help_text='Maximum allowable vessel draft in metres')),
                ('max_beam', models.FloatField(default=50.0, help_text='Maximum allowable vessel beam in metres')),
                ('max_loa', models.FloatField(default=300.0, help_text='Maximum Length Overall in metres')),
                ('ships_currently_at_port', models.PositiveIntegerField(default=0)),
                ('expected_incoming_shipments', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_nautical_miles', models.PositiveIntegerField(default=0, help_text='Approximate route distance in nautical miles')),
                ('typical_transit_days', models.PositiveIntegerField(default=0, help_text='Typical voyage duration in days')),
                ('destination_port', models.ForeignKey(limit_choices_to={'port_type': 'destination'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='app.port')),
                ('origin_port', models.ForeignKey(limit_choices_to={'port_type': 'origin'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='app.port')),
            ],
            options={
                'ordering': ['origin_port__name', 'destination_port__name'],
                'unique_together': {('origin_port', 'destination_port')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('coking_coal', 'Coking Coal'), ('non_coking_coal', 'Non-Coking Coal'), ('iron_ore', 'Iron Ore'), ('limestone', 'Limestone')], max_length=30)),
                ('signal', models.CharField(choices=[('BUY_NOW', '🟢 BUY NOW'), ('WAIT', '🟠 WAIT / STAGGER'), ('DELAY', '🔴 DELAY BOOKING')], max_length=20)),
                ('rationale', models.TextField(help_text='Human-readable explanation of the recommendation')),
                ('financial_impact_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated savings/loss in USD', max_digits=14, null=True)),
                ('financial_impact_inr', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated savings/loss in INR', max_digits=16, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app.route')),
                ('vessel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vessel')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('coking_coal', 'Coking Coal'), ('non_coking_coal', 'Non-Coking Coal'), ('iron_ore', 'Iron Ore'), ('limestone', 'Limestone')], max_length=30)),
                ('volume_mt', models.DecimalField(decimal_places=2, help_text='Cargo volume in Metric Tons', max_digits=12)),
                ('base_freight_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bunker_adjustment_factor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('port_handling_charges', models.DecimalField(decimal_places=2, max_digits=14)),
                ('demurrage_buffer', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_landed_cost_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_landed_cost_inr', models.DecimalField(decimal_places=2, max_digits=16)),
                ('usd_to_inr_rate', models.DecimalField(decimal_places=2, default=83.0, help_text='USD to INR exchange rate used for conversion', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdowns', to='app.route')),
                ('vessel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('coking_coal', 'Coking Coal'), ('non_coking_coal', 'Non-Coking Coal'), ('iron_ore', 'Iron Ore'), ('limestone', 'Limestone')], max_length=30)),
                ('date', models.DateField()),
                ('rate_usd_per_ton', models.DecimalField(decimal_places=2, help_text='Freight rate in USD per Metric Ton', max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='app.route')),
                ('vessel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='app.vessel')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['route', 'vessel_class', 'commodity', 'date'], name='app_freight_route_i_d8db69_idx')],
                'unique_together': {('route', 'vessel_class', 'commodity', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('coking_coal', 'Coking Coal'), ('non_coking_coal', 'Non-Coking Coal'), ('iron_ore', 'Iron Ore'), ('limestone', 'Limestone')], max_length=30)),
                ('forecast_date', models.DateField(help_text='The date being predicted')),
                ('predicted_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_bound', models.DecimalField(decimal_places=2, help_text='Lower confidence interval bound', max_digits=10)),
                ('upper_bound', models.DecimalField(decimal_places=2, help_text='Upper confidence interval bound', max_digits=10)),
                ('horizon_days', models.PositiveIntegerField(choices=[(30, '30-day'), (60, '60-day'), (90, '90-day')], help_text='Forecast horizon this prediction belongs to')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='app.route')),
                ('vessel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='app.vessel')),
            ],
            options={
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['route', 'vessel_class', 'commodity', 'forecast_date'], name='app_forecas_route_i_6fd83e_idx')],
            },
        ),
    ]
