# Generated by Django 6.1.1 on 2026-09-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BunkerFuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('marine_gas_oil_usd', models.DecimalField(decimal_places=2, help_text='Marine Gas Oil price in USD per ton', max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
