# Generated by Django 6.1.1 on 2026-09-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bunkerfuelprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Observation date')),
                ('wind_speed_ms', models.FloatField(help_text='Mean wind speed in metres per second')),
                ('wave_height_m', models.FloatField(help_text='Significant wave height in metres')),
                ('rainfall_mm', models.FloatField(help_text='Total rainfall in millimetres')),
                ('storm_severity', models.PositiveIntegerField(default=0, help_text='Storm/severity indicator on a 0–5 scale (0 = calm)')),
                ('weather_impact_score', models.FloatField(help_text='Composite weather impact on freight operations, 0–10 scale')),
                ('port', models.ForeignKey(help_text='Destination port this observation applies to', limit_choices_to={'port_type': 'destination'}, on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='app.port')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['port', 'date'], name='app_weather_port_id_99e79d_idx')],
                'unique_together': {('port', 'date')},
            },
        ),
    ]
