# Generated by Django 6.1.1 on 2026-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunkerfuelprice',
            name='source',
            field=models.CharField(default='synthetic', help_text="Data source: 'synthetic' or 'oilpriceapi'", max_length=20),
        ),
        migrations.AddField(
            model_name='marketindex',
            name='source',
            field=models.CharField(default='synthetic', help_text="Data source: 'synthetic' or 'oilpriceapi'", max_length=20),
        ),
    ]
