# Generated by Django 6.1.1 on 2026-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bunkerfuelprice_source_marketindex_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunkerfuelprice',
            name='marine_gas_oil_usd',
            field=models.DecimalField(decimal_places=2, help_text='VLSFO price in USD per ton', max_digits=10),
        ),
    ]
