# Generated by Django 6.1.1 on 2026-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bunkerfuelprice_marine_gas_oil_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunkerfuelprice',
            name='ifo_180_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IFO 180 price in USD per ton', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bunkerfuelprice',
            name='ifo_380_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IFO 380 price in USD per ton', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bunkerfuelprice',
            name='vlsfo_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VLSFO price in USD per ton', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bunkerfuelprice',
            name='marine_gas_oil_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MGO price in USD per ton', max_digits=10, null=True),
        ),
    ]
